<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Zaliczenie</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b1d379df-6681-4ddc-be60-2ae7c87aaa0e</testSuiteGuid>
   <testCaseLink>
      <guid>f7f7f704-86d4-4fe4-a095-ba9d6f583f28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/saucedemo_logowanie_bledne/saucedemo_logowanie_bledne_dane</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44fa87bd-5402-4fd0-83b0-803e2bccdeb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7baf11c9-610f-44fe-bbf1-f81b85de1303</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c503cf9-57d1-43ec-b7ae-48dcbc47d01e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/sauce_demo_zamowienie/saucedemo_zlozenia zamowienia</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e648f81f-a9e0-40b3-a2d5-0bdf2d02fc7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>359d0044-d57e-48d1-b332-7f0499b81bec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a3dbcd4-60c9-4647-841a-84874aaac4e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e84c5b5-2880-412a-b172-86b163c41077</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eba1a673-3fc4-4e37-b50a-f43192372b0e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
